---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
implicit:
  - Пользователь должен иметь возможность зарегестрироваться в приложении.
  - Пользователь должен иметь возможность заказать товар.
  - Пользователь должен иметь возможность получить обратную связь о статусе заказа.
  - Пользователь должен иметь возможность отменить заказ.
  - Пользователь должен иметь возможность откладывать товар в избранное.
  - Информация, представленная на сайте, должна соотвествовать нормам законодательства Российской Федерации.
  - Информация о товарах на сайте должна быть представлена на русском и английском языках.
